name: Release droidherd-fork

on:
  - push

#  release:
#    types: [created, workflow_dispatch]

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_LOGIN }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  DOCKER_REPOSITORY: ${{secrets.DOCKER_REPOSITORY}}
  IMAGE_NAME: droidherd-fork
  MY_GITHUB_REF_NAME: "release-0.0.1"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check repository and tag
        run: .github/scripts/release-env-check.sh

      - name: Set build version
        run: |
          echo "BUILD_VERSION=$(echo $MY_GITHUB_REF_NAME | grep -Eo '[0-9]\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      - name: Show and check version
        run: |
          echo "Evaluated version: [$BUILD_VERSION]"
          if [[ -z "$BUILD_VERSION" ]]; then exit 1; fi

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: ./gradlew assemble test

      - name: Generate sign key for publishing
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SIGN_OSSRH_GRADLE_PROPERTIES: ${{ secrets.SIGN_OSSRH_GRADLE_PROPERTIES }}
        run: |
          echo "$GPG_KEY" | base64 --decode > /tmp/secring.gpg
          mkdir -p ~/.gradle
          echo -en "$SIGN_OSSRH_GRADLE_PROPERTIES" > ~/.gradle/gradle.properties

      - name: Execute Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Psigning.secretKeyRingFile=/tmp/secring.gpg
        env:
          RELEASE_REPOSITORY_URL: https://oss.sonatype.org/service/local/staging/deploy/maven2/

#      - name: Execute Gradle nexus staging release
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: closeAndReleaseRepository
#        env:
#          RELEASE_REPOSITORY_URL: https://oss.sonatype.org/service/local/

      - name: Docker build and push
        run: |
          echo '${{ secrets.DOCKER_REPOSITORY_PASSWORD }}' | docker login -u $DOCKER_REPOSITORY --password-stdin
          docker build . --file ./OssDockerfile --tag $DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:${BUILD_VERSION}
          echo "docker push $DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:${BUILD_VERSION}"
          docker tag $DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:${BUILD_VERSION} $DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:latest
          echo "Update latest tag $DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME"  
          docker push $DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:latest
